/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  sym_url = 2,
  anon_sym_STAR_STAR = 3,
  anon_sym___ = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_heading_marker = 8,
  sym_newline = 9,
  sym_document = 10,
  sym__inline_content = 11,
  sym__block_content = 12,
  sym_bold = 13,
  sym_italic = 14,
  sym_link = 15,
  aux_sym__heading_content = 16,
  sym_heading = 17,
  aux_sym_document_repeat1 = 18,
  aux_sym_document_repeat2 = 19,
  aux_sym_bold_repeat1 = 20,
  aux_sym_italic_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [sym_url] = "url",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK_LPAREN] = "](",
  [anon_sym_RPAREN] = ")",
  [sym_heading_marker] = "heading_marker",
  [sym_newline] = "newline",
  [sym_document] = "document",
  [sym__inline_content] = "_inline_content",
  [sym__block_content] = "_block_content",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_link] = "link",
  [aux_sym__heading_content] = "_heading_content",
  [sym_heading] = "heading",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_bold_repeat1] = "bold_repeat1",
  [aux_sym_italic_repeat1] = "italic_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [sym_url] = sym_url,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK_LPAREN] = anon_sym_RBRACK_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_heading_marker] = sym_heading_marker,
  [sym_newline] = sym_newline,
  [sym_document] = sym_document,
  [sym__inline_content] = sym__inline_content,
  [sym__block_content] = sym__block_content,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_link] = sym_link,
  [aux_sym__heading_content] = aux_sym__heading_content,
  [sym_heading] = sym_heading,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_bold_repeat1] = aux_sym_bold_repeat1,
  [aux_sym_italic_repeat1] = aux_sym_italic_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_content] = {
    .visible = false,
    .named = true,
  },
  [sym__block_content] = {
    .visible = false,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__heading_content] = {
    .visible = false,
    .named = false,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bold_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_italic_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '\n', 21,
        '#', 20,
        ')', 14,
        '*', 2,
        '[', 12,
        '\\', 5,
        ']', 1,
        '_', 4,
      );
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead)) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '_') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_heading_marker);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_heading_marker] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(19),
    [sym__inline_content] = STATE(4),
    [sym__block_content] = STATE(20),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_link] = STATE(4),
    [sym_heading] = STATE(20),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_document_repeat2] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_heading_marker] = ACTIONS(13),
    [sym_newline] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__inline_content] = STATE(4),
    [sym__block_content] = STATE(20),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_link] = STATE(4),
    [sym_heading] = STATE(20),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_document_repeat2] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_text] = ACTIONS(5),
    [anon_sym_STAR_STAR] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_heading_marker] = ACTIONS(13),
    [sym_newline] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__inline_content] = STATE(4),
    [sym__block_content] = STATE(20),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_link] = STATE(4),
    [sym_heading] = STATE(20),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_document_repeat2] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_text] = ACTIONS(23),
    [anon_sym_STAR_STAR] = ACTIONS(26),
    [anon_sym___] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(32),
    [sym_heading_marker] = ACTIONS(35),
    [sym_newline] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      anon_sym_STAR_STAR,
    ACTIONS(9), 1,
      anon_sym___,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      sym_text,
    ACTIONS(43), 1,
      sym_newline,
    STATE(6), 5,
      sym__inline_content,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_document_repeat1,
  [23] = 6,
    ACTIONS(7), 1,
      anon_sym_STAR_STAR,
    ACTIONS(9), 1,
      anon_sym___,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      sym_text,
    ACTIONS(47), 1,
      sym_newline,
    STATE(7), 5,
      sym__inline_content,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym__heading_content,
  [46] = 6,
    ACTIONS(49), 1,
      sym_text,
    ACTIONS(52), 1,
      anon_sym_STAR_STAR,
    ACTIONS(55), 1,
      anon_sym___,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      sym_newline,
    STATE(6), 5,
      sym__inline_content,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_document_repeat1,
  [69] = 6,
    ACTIONS(63), 1,
      sym_text,
    ACTIONS(66), 1,
      anon_sym_STAR_STAR,
    ACTIONS(69), 1,
      anon_sym___,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      sym_newline,
    STATE(7), 5,
      sym__inline_content,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym__heading_content,
  [92] = 5,
    ACTIONS(7), 1,
      anon_sym_STAR_STAR,
    ACTIONS(9), 1,
      anon_sym___,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(77), 1,
      sym_text,
    STATE(5), 5,
      sym__inline_content,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym__heading_content,
  [112] = 5,
    ACTIONS(9), 1,
      anon_sym___,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 1,
      sym_text,
    ACTIONS(81), 1,
      anon_sym_STAR_STAR,
    STATE(13), 3,
      sym_italic,
      sym_link,
      aux_sym_bold_repeat1,
  [130] = 5,
    ACTIONS(7), 1,
      anon_sym_STAR_STAR,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      sym_text,
    ACTIONS(85), 1,
      anon_sym___,
    STATE(12), 3,
      sym_bold,
      sym_link,
      aux_sym_italic_repeat1,
  [148] = 1,
    ACTIONS(21), 7,
      ts_builtin_sym_end,
      sym_text,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_LBRACK,
      sym_heading_marker,
      sym_newline,
  [158] = 5,
    ACTIONS(87), 1,
      sym_text,
    ACTIONS(90), 1,
      anon_sym_STAR_STAR,
    ACTIONS(93), 1,
      anon_sym___,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    STATE(12), 3,
      sym_bold,
      sym_link,
      aux_sym_italic_repeat1,
  [176] = 5,
    ACTIONS(98), 1,
      sym_text,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(103), 1,
      anon_sym___,
    ACTIONS(106), 1,
      anon_sym_LBRACK,
    STATE(13), 3,
      sym_italic,
      sym_link,
      aux_sym_bold_repeat1,
  [194] = 4,
    ACTIONS(7), 1,
      anon_sym_STAR_STAR,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      sym_text,
    STATE(10), 3,
      sym_bold,
      sym_link,
      aux_sym_italic_repeat1,
  [209] = 4,
    ACTIONS(9), 1,
      anon_sym___,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      sym_text,
    STATE(9), 3,
      sym_italic,
      sym_link,
      aux_sym_bold_repeat1,
  [224] = 1,
    ACTIONS(113), 5,
      sym_text,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_LBRACK,
      sym_newline,
  [232] = 1,
    ACTIONS(115), 5,
      sym_text,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_LBRACK,
      sym_newline,
  [240] = 1,
    ACTIONS(117), 5,
      sym_text,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_LBRACK,
      sym_newline,
  [248] = 1,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
  [252] = 1,
    ACTIONS(43), 1,
      sym_newline,
  [256] = 1,
    ACTIONS(121), 1,
      sym_text,
  [260] = 1,
    ACTIONS(123), 1,
      sym_url,
  [264] = 1,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
  [268] = 1,
    ACTIONS(127), 1,
      anon_sym_RBRACK_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 23,
  [SMALL_STATE(6)] = 46,
  [SMALL_STATE(7)] = 69,
  [SMALL_STATE(8)] = 92,
  [SMALL_STATE(9)] = 112,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 158,
  [SMALL_STATE(13)] = 176,
  [SMALL_STATE(14)] = 194,
  [SMALL_STATE(15)] = 209,
  [SMALL_STATE(16)] = 224,
  [SMALL_STATE(17)] = 232,
  [SMALL_STATE(18)] = 240,
  [SMALL_STATE(19)] = 248,
  [SMALL_STATE(20)] = 252,
  [SMALL_STATE(21)] = 256,
  [SMALL_STATE(22)] = 260,
  [SMALL_STATE(23)] = 264,
  [SMALL_STATE(24)] = 268,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(14),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__heading_content, 2, 0, 0), SHIFT_REPEAT(7),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__heading_content, 2, 0, 0), SHIFT_REPEAT(15),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__heading_content, 2, 0, 0), SHIFT_REPEAT(14),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__heading_content, 2, 0, 0), SHIFT_REPEAT(21),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__heading_content, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
