/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 76
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_document_token1 = 1,
  sym__normal_text = 2,
  sym__link_text = 3,
  sym_url = 4,
  aux_sym_variable_token1 = 5,
  aux_sym_variable_token2 = 6,
  aux_sym_variable_token3 = 7,
  aux_sym_variable_token4 = 8,
  anon_sym_STAR = 9,
  anon_sym__ = 10,
  anon_sym_DOLLARlink = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK_LPAREN = 13,
  anon_sym_RPAREN = 14,
  sym_heading_marker = 15,
  aux_sym_heading_token1 = 16,
  aux_sym_unordered_list_token1 = 17,
  aux_sym_unordered_list_token2 = 18,
  aux_sym_unordered_list_item_token1 = 19,
  aux_sym_unordered_list_item_token2 = 20,
  aux_sym_ordered_list_token1 = 21,
  aux_sym_ordered_list_item_token1 = 22,
  aux_sym_blockquote_token1 = 23,
  sym_hr = 24,
  sym_document = 25,
  sym__inline_content = 26,
  sym__block_content = 27,
  sym_variable = 28,
  sym_bold = 29,
  sym_italic = 30,
  sym_link = 31,
  sym_heading = 32,
  sym_unordered_list = 33,
  sym_unordered_list_item = 34,
  sym_ordered_list = 35,
  sym_ordered_list_item = 36,
  sym_paragraph = 37,
  sym_blockquote = 38,
  aux_sym_document_repeat1 = 39,
  aux_sym_bold_repeat1 = 40,
  aux_sym_italic_repeat1 = 41,
  aux_sym_heading_repeat1 = 42,
  aux_sym_unordered_list_repeat1 = 43,
  aux_sym_ordered_list_repeat1 = 44,
  aux_sym_paragraph_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_document_token1] = "document_token1",
  [sym__normal_text] = "text",
  [sym__link_text] = "text",
  [sym_url] = "url",
  [aux_sym_variable_token1] = "variable_token1",
  [aux_sym_variable_token2] = "variable_token2",
  [aux_sym_variable_token3] = "variable_token3",
  [aux_sym_variable_token4] = "variable_token4",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_DOLLARlink] = "$link",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK_LPAREN] = "](",
  [anon_sym_RPAREN] = ")",
  [sym_heading_marker] = "heading_marker",
  [aux_sym_heading_token1] = "heading_token1",
  [aux_sym_unordered_list_token1] = "unordered_list_token1",
  [aux_sym_unordered_list_token2] = "unordered_list_token2",
  [aux_sym_unordered_list_item_token1] = "attr",
  [aux_sym_unordered_list_item_token2] = "unordered_list_item_token2",
  [aux_sym_ordered_list_token1] = "ordered_list_token1",
  [aux_sym_ordered_list_item_token1] = "ordered_list_item_token1",
  [aux_sym_blockquote_token1] = "blockquote_token1",
  [sym_hr] = "hr",
  [sym_document] = "document",
  [sym__inline_content] = "_inline_content",
  [sym__block_content] = "_block_content",
  [sym_variable] = "variable",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_link] = "link",
  [sym_heading] = "heading",
  [sym_unordered_list] = "unordered_list",
  [sym_unordered_list_item] = "unordered_list_item",
  [sym_ordered_list] = "ordered_list",
  [sym_ordered_list_item] = "ordered_list_item",
  [sym_paragraph] = "paragraph",
  [sym_blockquote] = "blockquote",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_bold_repeat1] = "bold_repeat1",
  [aux_sym_italic_repeat1] = "italic_repeat1",
  [aux_sym_heading_repeat1] = "heading_repeat1",
  [aux_sym_unordered_list_repeat1] = "unordered_list_repeat1",
  [aux_sym_ordered_list_repeat1] = "ordered_list_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_document_token1] = aux_sym_document_token1,
  [sym__normal_text] = sym__normal_text,
  [sym__link_text] = sym__normal_text,
  [sym_url] = sym_url,
  [aux_sym_variable_token1] = aux_sym_variable_token1,
  [aux_sym_variable_token2] = aux_sym_variable_token2,
  [aux_sym_variable_token3] = aux_sym_variable_token3,
  [aux_sym_variable_token4] = aux_sym_variable_token4,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_DOLLARlink] = anon_sym_DOLLARlink,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK_LPAREN] = anon_sym_RBRACK_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_heading_marker] = sym_heading_marker,
  [aux_sym_heading_token1] = aux_sym_heading_token1,
  [aux_sym_unordered_list_token1] = aux_sym_unordered_list_token1,
  [aux_sym_unordered_list_token2] = aux_sym_unordered_list_token2,
  [aux_sym_unordered_list_item_token1] = aux_sym_unordered_list_item_token1,
  [aux_sym_unordered_list_item_token2] = aux_sym_unordered_list_item_token2,
  [aux_sym_ordered_list_token1] = aux_sym_ordered_list_token1,
  [aux_sym_ordered_list_item_token1] = aux_sym_ordered_list_item_token1,
  [aux_sym_blockquote_token1] = aux_sym_blockquote_token1,
  [sym_hr] = sym_hr,
  [sym_document] = sym_document,
  [sym__inline_content] = sym__inline_content,
  [sym__block_content] = sym__block_content,
  [sym_variable] = sym_variable,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_link] = sym_link,
  [sym_heading] = sym_heading,
  [sym_unordered_list] = sym_unordered_list,
  [sym_unordered_list_item] = sym_unordered_list_item,
  [sym_ordered_list] = sym_ordered_list,
  [sym_ordered_list_item] = sym_ordered_list_item,
  [sym_paragraph] = sym_paragraph,
  [sym_blockquote] = sym_blockquote,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_bold_repeat1] = aux_sym_bold_repeat1,
  [aux_sym_italic_repeat1] = aux_sym_italic_repeat1,
  [aux_sym_heading_repeat1] = aux_sym_heading_repeat1,
  [aux_sym_unordered_list_repeat1] = aux_sym_unordered_list_repeat1,
  [aux_sym_ordered_list_repeat1] = aux_sym_ordered_list_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__normal_text] = {
    .visible = true,
    .named = true,
  },
  [sym__link_text] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLARlink] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_heading_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unordered_list_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unordered_list_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unordered_list_item_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unordered_list_item_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ordered_list_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ordered_list_item_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blockquote_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_hr] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_content] = {
    .visible = false,
    .named = true,
  },
  [sym__block_content] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_unordered_list] = {
    .visible = true,
    .named = true,
  },
  [sym_unordered_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_ordered_list] = {
    .visible = true,
    .named = true,
  },
  [sym_ordered_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_blockquote] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bold_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_italic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unordered_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ordered_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [4] = sym_url,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_variable, 2,
    sym_variable,
    sym_url,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 50,
  [51] = 46,
  [52] = 48,
  [53] = 34,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 33,
  [68] = 68,
  [69] = 38,
  [70] = 70,
  [71] = 71,
  [72] = 61,
  [73] = 64,
  [74] = 74,
  [75] = 56,
};

static const TSCharacterRange sym__normal_text_character_set_1[] = {
  {0, '\t'}, {0x0b, '"'}, {'%', ')'}, {'+', '='}, {'?', '^'}, {'`', 'z'}, {'|', 0x17e}, {0x180, 0x2129},
  {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\n', 26,
        ' ', 31,
        '#', 45,
        '$', 9,
        ')', 39,
        '*', 34,
        '-', 52,
        '>', 5,
        '[', 37,
        ']', 49,
        '_', 35,
        '{', 30,
        '}', 33,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(31);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(55);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ')' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(18);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '[') ADVANCE(2);
      END_STATE();
    case 14:
      if (lookahead == '[') ADVANCE(3);
      END_STATE();
    case 15:
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'k') ADVANCE(36);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(28);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\n', 26,
        '#', 45,
        '$', 9,
        '*', 34,
        '>', 5,
        '\\', 21,
        '_', 35,
        '{', 30,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_document_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__normal_text);
      if (lookahead == '\\') ADVANCE(21);
      if ((!eof && set_contains(sym__normal_text_character_set_1, 9, lookahead))) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__link_text);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_url);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_variable_token2);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_variable_token3);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_variable_token4);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOLLARlink);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK_LPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_heading_marker);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_unordered_list_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_unordered_list_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_unordered_list_token2);
      if (lookahead == '(') ADVANCE(38);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_unordered_list_item_token1);
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_unordered_list_item_token1);
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == ']') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_unordered_list_item_token2);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_ordered_list_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_ordered_list_item_token1);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_blockquote_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_hr);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 24},
  [22] = {.lex_state = 24},
  [23] = {.lex_state = 24},
  [24] = {.lex_state = 24},
  [25] = {.lex_state = 24},
  [26] = {.lex_state = 24},
  [27] = {.lex_state = 51},
  [28] = {.lex_state = 51},
  [29] = {.lex_state = 51},
  [30] = {.lex_state = 51},
  [31] = {.lex_state = 24},
  [32] = {.lex_state = 24},
  [33] = {.lex_state = 24},
  [34] = {.lex_state = 24},
  [35] = {.lex_state = 24},
  [36] = {.lex_state = 51},
  [37] = {.lex_state = 51},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 24},
  [40] = {.lex_state = 24},
  [41] = {.lex_state = 51},
  [42] = {.lex_state = 51},
  [43] = {.lex_state = 51},
  [44] = {.lex_state = 51},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 15},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_document_token1] = ACTIONS(1),
    [aux_sym_variable_token1] = ACTIONS(1),
    [aux_sym_variable_token2] = ACTIONS(1),
    [aux_sym_variable_token4] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DOLLARlink] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_heading_marker] = ACTIONS(1),
    [aux_sym_heading_token1] = ACTIONS(1),
    [aux_sym_unordered_list_token1] = ACTIONS(1),
    [aux_sym_unordered_list_token2] = ACTIONS(1),
    [aux_sym_unordered_list_item_token2] = ACTIONS(1),
    [aux_sym_ordered_list_token1] = ACTIONS(1),
    [aux_sym_ordered_list_item_token1] = ACTIONS(1),
    [aux_sym_blockquote_token1] = ACTIONS(1),
    [sym_hr] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(68),
    [sym__inline_content] = STATE(6),
    [sym__block_content] = STATE(54),
    [sym_variable] = STATE(6),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [sym_link] = STATE(6),
    [sym_heading] = STATE(54),
    [sym_unordered_list] = STATE(54),
    [sym_ordered_list] = STATE(54),
    [sym_paragraph] = STATE(54),
    [sym_blockquote] = STATE(54),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_heading_repeat1] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_document_token1] = ACTIONS(5),
    [sym__normal_text] = ACTIONS(7),
    [aux_sym_variable_token1] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_DOLLARlink] = ACTIONS(15),
    [sym_heading_marker] = ACTIONS(17),
    [aux_sym_unordered_list_token1] = ACTIONS(19),
    [aux_sym_ordered_list_token1] = ACTIONS(21),
    [aux_sym_blockquote_token1] = ACTIONS(23),
    [sym_hr] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__inline_content] = STATE(6),
    [sym__block_content] = STATE(54),
    [sym_variable] = STATE(6),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [sym_link] = STATE(6),
    [sym_heading] = STATE(54),
    [sym_unordered_list] = STATE(54),
    [sym_ordered_list] = STATE(54),
    [sym_paragraph] = STATE(54),
    [sym_blockquote] = STATE(54),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_heading_repeat1] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_document_token1] = ACTIONS(29),
    [sym__normal_text] = ACTIONS(7),
    [aux_sym_variable_token1] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_DOLLARlink] = ACTIONS(15),
    [sym_heading_marker] = ACTIONS(17),
    [aux_sym_unordered_list_token1] = ACTIONS(19),
    [aux_sym_ordered_list_token1] = ACTIONS(21),
    [aux_sym_blockquote_token1] = ACTIONS(23),
    [sym_hr] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym__inline_content] = STATE(6),
    [sym__block_content] = STATE(54),
    [sym_variable] = STATE(6),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [sym_link] = STATE(6),
    [sym_heading] = STATE(54),
    [sym_unordered_list] = STATE(54),
    [sym_ordered_list] = STATE(54),
    [sym_paragraph] = STATE(54),
    [sym_blockquote] = STATE(54),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_heading_repeat1] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [aux_sym_document_token1] = ACTIONS(33),
    [sym__normal_text] = ACTIONS(36),
    [aux_sym_variable_token1] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(42),
    [anon_sym__] = ACTIONS(45),
    [anon_sym_DOLLARlink] = ACTIONS(48),
    [sym_heading_marker] = ACTIONS(51),
    [aux_sym_unordered_list_token1] = ACTIONS(54),
    [aux_sym_ordered_list_token1] = ACTIONS(57),
    [aux_sym_blockquote_token1] = ACTIONS(60),
    [sym_hr] = ACTIONS(63),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      sym__normal_text,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(66), 1,
      aux_sym_document_token1,
    STATE(5), 1,
      aux_sym_paragraph_repeat1,
    STATE(6), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [30] = 8,
    ACTIONS(68), 1,
      aux_sym_document_token1,
    ACTIONS(70), 1,
      sym__normal_text,
    ACTIONS(73), 1,
      aux_sym_variable_token1,
    ACTIONS(76), 1,
      anon_sym_STAR,
    ACTIONS(79), 1,
      anon_sym__,
    ACTIONS(82), 1,
      anon_sym_DOLLARlink,
    STATE(5), 1,
      aux_sym_paragraph_repeat1,
    STATE(6), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [60] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(85), 1,
      aux_sym_document_token1,
    ACTIONS(87), 1,
      sym__normal_text,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [87] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(87), 1,
      sym__normal_text,
    ACTIONS(89), 1,
      aux_sym_document_token1,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [114] = 1,
    ACTIONS(31), 12,
      ts_builtin_sym_end,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
      sym_heading_marker,
      aux_sym_unordered_list_token1,
      aux_sym_ordered_list_token1,
      aux_sym_blockquote_token1,
      sym_hr,
  [129] = 7,
    ACTIONS(91), 1,
      aux_sym_document_token1,
    ACTIONS(93), 1,
      sym__normal_text,
    ACTIONS(96), 1,
      aux_sym_variable_token1,
    ACTIONS(99), 1,
      anon_sym_STAR,
    ACTIONS(102), 1,
      anon_sym__,
    ACTIONS(105), 1,
      anon_sym_DOLLARlink,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [156] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(87), 1,
      sym__normal_text,
    ACTIONS(108), 1,
      aux_sym_document_token1,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [183] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(87), 1,
      sym__normal_text,
    ACTIONS(110), 1,
      aux_sym_document_token1,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [210] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(87), 1,
      sym__normal_text,
    ACTIONS(112), 1,
      aux_sym_document_token1,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [237] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(87), 1,
      sym__normal_text,
    ACTIONS(114), 1,
      aux_sym_document_token1,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [264] = 7,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(87), 1,
      sym__normal_text,
    ACTIONS(116), 1,
      aux_sym_document_token1,
    STATE(9), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [291] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(118), 1,
      sym__normal_text,
    STATE(7), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [315] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(120), 1,
      sym__normal_text,
    STATE(12), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [339] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(122), 1,
      sym__normal_text,
    STATE(14), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [363] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(124), 1,
      sym__normal_text,
    STATE(13), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [387] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(126), 1,
      sym__normal_text,
    STATE(11), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [411] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(128), 1,
      sym__normal_text,
    STATE(10), 6,
      sym__inline_content,
      sym_variable,
      sym_bold,
      sym_italic,
      sym_link,
      aux_sym_heading_repeat1,
  [435] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(130), 1,
      sym__normal_text,
    ACTIONS(132), 1,
      anon_sym_STAR,
    STATE(24), 4,
      sym_variable,
      sym_italic,
      sym_link,
      aux_sym_bold_repeat1,
  [457] = 6,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(134), 1,
      sym__normal_text,
    ACTIONS(136), 1,
      anon_sym__,
    STATE(23), 4,
      sym_variable,
      sym_bold,
      sym_link,
      aux_sym_italic_repeat1,
  [479] = 6,
    ACTIONS(138), 1,
      sym__normal_text,
    ACTIONS(141), 1,
      aux_sym_variable_token1,
    ACTIONS(144), 1,
      anon_sym_STAR,
    ACTIONS(147), 1,
      anon_sym__,
    ACTIONS(149), 1,
      anon_sym_DOLLARlink,
    STATE(23), 4,
      sym_variable,
      sym_bold,
      sym_link,
      aux_sym_italic_repeat1,
  [501] = 6,
    ACTIONS(152), 1,
      sym__normal_text,
    ACTIONS(155), 1,
      aux_sym_variable_token1,
    ACTIONS(158), 1,
      anon_sym_STAR,
    ACTIONS(160), 1,
      anon_sym__,
    ACTIONS(163), 1,
      anon_sym_DOLLARlink,
    STATE(24), 4,
      sym_variable,
      sym_italic,
      sym_link,
      aux_sym_bold_repeat1,
  [523] = 5,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(166), 1,
      sym__normal_text,
    STATE(22), 4,
      sym_variable,
      sym_bold,
      sym_link,
      aux_sym_italic_repeat1,
  [542] = 5,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_DOLLARlink,
    ACTIONS(168), 1,
      sym__normal_text,
    STATE(21), 4,
      sym_variable,
      sym_italic,
      sym_link,
      aux_sym_bold_repeat1,
  [561] = 5,
    ACTIONS(170), 1,
      aux_sym_unordered_list_token2,
    ACTIONS(172), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(175), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(178), 1,
      aux_sym_ordered_list_item_token1,
    STATE(27), 3,
      sym_unordered_list_item,
      sym_ordered_list_item,
      aux_sym_ordered_list_repeat1,
  [579] = 5,
    ACTIONS(181), 1,
      aux_sym_unordered_list_token2,
    ACTIONS(183), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(186), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(189), 1,
      aux_sym_ordered_list_item_token1,
    STATE(28), 3,
      sym_unordered_list_item,
      sym_ordered_list_item,
      aux_sym_unordered_list_repeat1,
  [597] = 5,
    ACTIONS(192), 1,
      aux_sym_unordered_list_token2,
    ACTIONS(194), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(196), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(198), 1,
      aux_sym_ordered_list_item_token1,
    STATE(28), 3,
      sym_unordered_list_item,
      sym_ordered_list_item,
      aux_sym_unordered_list_repeat1,
  [615] = 5,
    ACTIONS(194), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(196), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(198), 1,
      aux_sym_ordered_list_item_token1,
    ACTIONS(200), 1,
      aux_sym_unordered_list_token2,
    STATE(27), 3,
      sym_unordered_list_item,
      sym_ordered_list_item,
      aux_sym_ordered_list_repeat1,
  [633] = 1,
    ACTIONS(68), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [642] = 1,
    ACTIONS(202), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [651] = 1,
    ACTIONS(204), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [660] = 1,
    ACTIONS(206), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [669] = 1,
    ACTIONS(208), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [678] = 4,
    ACTIONS(194), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(196), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(198), 1,
      aux_sym_ordered_list_item_token1,
    STATE(30), 3,
      sym_unordered_list_item,
      sym_ordered_list_item,
      aux_sym_ordered_list_repeat1,
  [693] = 4,
    ACTIONS(194), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(196), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(198), 1,
      aux_sym_ordered_list_item_token1,
    STATE(29), 3,
      sym_unordered_list_item,
      sym_ordered_list_item,
      aux_sym_unordered_list_repeat1,
  [708] = 1,
    ACTIONS(210), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [717] = 1,
    ACTIONS(212), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [726] = 1,
    ACTIONS(214), 6,
      aux_sym_document_token1,
      sym__normal_text,
      aux_sym_variable_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOLLARlink,
  [735] = 2,
    ACTIONS(218), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(216), 3,
      aux_sym_unordered_list_token2,
      aux_sym_unordered_list_item_token2,
      aux_sym_ordered_list_item_token1,
  [744] = 2,
    ACTIONS(222), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(220), 3,
      aux_sym_unordered_list_token2,
      aux_sym_unordered_list_item_token2,
      aux_sym_ordered_list_item_token1,
  [753] = 2,
    ACTIONS(226), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(224), 3,
      aux_sym_unordered_list_token2,
      aux_sym_unordered_list_item_token2,
      aux_sym_ordered_list_item_token1,
  [762] = 2,
    ACTIONS(230), 1,
      aux_sym_unordered_list_item_token1,
    ACTIONS(228), 3,
      aux_sym_unordered_list_token2,
      aux_sym_unordered_list_item_token2,
      aux_sym_ordered_list_item_token1,
  [771] = 3,
    ACTIONS(232), 1,
      sym_url,
    ACTIONS(234), 1,
      aux_sym_variable_token1,
    STATE(58), 1,
      sym_variable,
  [781] = 2,
    ACTIONS(236), 1,
      aux_sym_variable_token2,
    ACTIONS(238), 1,
      aux_sym_variable_token4,
  [788] = 2,
    ACTIONS(240), 1,
      aux_sym_variable_token2,
    ACTIONS(242), 1,
      aux_sym_variable_token3,
  [795] = 2,
    ACTIONS(244), 1,
      aux_sym_variable_token2,
    ACTIONS(246), 1,
      aux_sym_variable_token4,
  [802] = 2,
    ACTIONS(248), 1,
      aux_sym_variable_token2,
    ACTIONS(250), 1,
      aux_sym_variable_token3,
  [809] = 2,
    ACTIONS(252), 1,
      aux_sym_unordered_list_item_token2,
    ACTIONS(254), 1,
      aux_sym_ordered_list_item_token1,
  [816] = 2,
    ACTIONS(256), 1,
      aux_sym_variable_token2,
    ACTIONS(258), 1,
      aux_sym_variable_token4,
  [823] = 2,
    ACTIONS(260), 1,
      aux_sym_variable_token2,
    ACTIONS(262), 1,
      aux_sym_variable_token4,
  [830] = 1,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [834] = 1,
    ACTIONS(264), 1,
      aux_sym_document_token1,
  [838] = 1,
    ACTIONS(266), 1,
      aux_sym_heading_token1,
  [842] = 1,
    ACTIONS(268), 1,
      aux_sym_variable_token3,
  [846] = 1,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
  [850] = 1,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [854] = 1,
    ACTIONS(274), 1,
      sym__link_text,
  [858] = 1,
    ACTIONS(276), 1,
      aux_sym_document_token1,
  [862] = 1,
    ACTIONS(246), 1,
      aux_sym_variable_token4,
  [866] = 1,
    ACTIONS(278), 1,
      aux_sym_document_token1,
  [870] = 1,
    ACTIONS(280), 1,
      aux_sym_heading_token1,
  [874] = 1,
    ACTIONS(282), 1,
      aux_sym_variable_token4,
  [878] = 1,
    ACTIONS(284), 1,
      anon_sym_RBRACK_LPAREN,
  [882] = 1,
    ACTIONS(286), 1,
      anon_sym_LBRACK,
  [886] = 1,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [890] = 1,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
  [894] = 1,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
  [898] = 1,
    ACTIONS(290), 1,
      aux_sym_heading_token1,
  [902] = 1,
    ACTIONS(292), 1,
      aux_sym_heading_token1,
  [906] = 1,
    ACTIONS(262), 1,
      aux_sym_variable_token4,
  [910] = 1,
    ACTIONS(294), 1,
      aux_sym_variable_token4,
  [914] = 1,
    ACTIONS(296), 1,
      aux_sym_heading_token1,
  [918] = 1,
    ACTIONS(298), 1,
      aux_sym_variable_token3,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 87,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 129,
  [SMALL_STATE(10)] = 156,
  [SMALL_STATE(11)] = 183,
  [SMALL_STATE(12)] = 210,
  [SMALL_STATE(13)] = 237,
  [SMALL_STATE(14)] = 264,
  [SMALL_STATE(15)] = 291,
  [SMALL_STATE(16)] = 315,
  [SMALL_STATE(17)] = 339,
  [SMALL_STATE(18)] = 363,
  [SMALL_STATE(19)] = 387,
  [SMALL_STATE(20)] = 411,
  [SMALL_STATE(21)] = 435,
  [SMALL_STATE(22)] = 457,
  [SMALL_STATE(23)] = 479,
  [SMALL_STATE(24)] = 501,
  [SMALL_STATE(25)] = 523,
  [SMALL_STATE(26)] = 542,
  [SMALL_STATE(27)] = 561,
  [SMALL_STATE(28)] = 579,
  [SMALL_STATE(29)] = 597,
  [SMALL_STATE(30)] = 615,
  [SMALL_STATE(31)] = 633,
  [SMALL_STATE(32)] = 642,
  [SMALL_STATE(33)] = 651,
  [SMALL_STATE(34)] = 660,
  [SMALL_STATE(35)] = 669,
  [SMALL_STATE(36)] = 678,
  [SMALL_STATE(37)] = 693,
  [SMALL_STATE(38)] = 708,
  [SMALL_STATE(39)] = 717,
  [SMALL_STATE(40)] = 726,
  [SMALL_STATE(41)] = 735,
  [SMALL_STATE(42)] = 744,
  [SMALL_STATE(43)] = 753,
  [SMALL_STATE(44)] = 762,
  [SMALL_STATE(45)] = 771,
  [SMALL_STATE(46)] = 781,
  [SMALL_STATE(47)] = 788,
  [SMALL_STATE(48)] = 795,
  [SMALL_STATE(49)] = 802,
  [SMALL_STATE(50)] = 809,
  [SMALL_STATE(51)] = 816,
  [SMALL_STATE(52)] = 823,
  [SMALL_STATE(53)] = 830,
  [SMALL_STATE(54)] = 834,
  [SMALL_STATE(55)] = 838,
  [SMALL_STATE(56)] = 842,
  [SMALL_STATE(57)] = 846,
  [SMALL_STATE(58)] = 850,
  [SMALL_STATE(59)] = 854,
  [SMALL_STATE(60)] = 858,
  [SMALL_STATE(61)] = 862,
  [SMALL_STATE(62)] = 866,
  [SMALL_STATE(63)] = 870,
  [SMALL_STATE(64)] = 874,
  [SMALL_STATE(65)] = 878,
  [SMALL_STATE(66)] = 882,
  [SMALL_STATE(67)] = 886,
  [SMALL_STATE(68)] = 890,
  [SMALL_STATE(69)] = 894,
  [SMALL_STATE(70)] = 898,
  [SMALL_STATE(71)] = 902,
  [SMALL_STATE(72)] = 906,
  [SMALL_STATE(73)] = 910,
  [SMALL_STATE(74)] = 914,
  [SMALL_STATE(75)] = 918,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blockquote, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 5, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ordered_list_item, 5, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ordered_list_item, 5, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ordered_list_item, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ordered_list_item, 4, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unordered_list_item, 4, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unordered_list_item, 4, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unordered_list_item, 5, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unordered_list_item, 5, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unordered_list, 3, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ordered_list, 3, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [288] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
